name: Maven CI/CD

on:
  push:
    branches: [master]
    tags:
     - 'v*.*.*'

jobs:
  release-build:
    name: Release Build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - name: Package
      shell: bash
      run: |
        cp README.md target/
        cd target/
        cp classes/version.properties .
        while read line; do
          if [[ "$line" =~ ^([^=:]+)=(.+)$ ]]; then
            key="${BASH_REMATCH[1]}"
            valid_key=`echo $key | tr "." "_"`
            value="${BASH_REMATCH[2]}"
            export "$valid_key"="$value"
          fi
        done < version.properties
        echo "creating zip for ${example_version}"
        zip -v rdapct-${example_version}.zip github-action-maven-tutorial-1.0-SNAPSHOT.jar version.properties README.md
        cd -
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/rdapct-*.zip
          README.md
          target/classes/version.properties
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
